# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

    
trigger:
- master

pool:
  vmImage: 'vs2017-win2016'
strategy:
  matrix:
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'


- script: |
    python -m pip install --upgrade pip
    pip install selenium
    pip install pytest
    pip install pytest_check
  displayName: 'Install dependencies'


- script: |
    pytest Testcases/SuperAdmin/test_1_login.py
  displayName: 'Login'
  continueOnError: true
  condition: always()

- script: |
    pytest Testcases/SuperAdmin/test__12_Upload_Csv_and_Validate.py
  displayName: 'Upload Translations and Validate'
  continueOnError: true
  condition: always()
