# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'
strategy:
  matrix:
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install selenium
    pip install pytest
    pip install pytest_check
  displayName: 'Install dependencies'

- script: |
    pytest Auto/Testcases/SuperAdmin/test_1_login.py
  displayName: 'Login'
  continueOnError: true
  condition: always()

- script: |
    pytest Auto/Testcases/SuperAdmin/test_2_Create_Users.py
  displayName: 'Create Users'
  continueOnError: true
  condition: always()

- script: |
    pytest Auto/Testcases/SuperAdmin/test_3_Edit_User.py
  displayName: 'Modify Users'
  continueOnError: true
  condition: always()

- script: |
    pytest Auto/Testcases/SuperAdmin/test_4_Delete_Users.py
  displayName: 'Delete Users'
  continueOnError: true
  condition: always()

- script: |
    pytest Auto/Testcases/SuperAdmin/test_5_Create_Project.py
  displayName: 'Create Project'
  continueOnError: false
  condition: always()

- script: |
    pytest Auto/Testcases/SuperAdmin/test_6_Preview_Localization.py
  displayName: 'Preview Localization'
  continueOnError: true
  condition: always()
  

- script: |
    pytest Auto/Testcases/SuperAdmin/test_7_Add_Exclusion_and_Validate.py
  displayName: 'Validate Added Exclusion'
  continueOnError: true
  condition: always()

- script: |
    pytest Auto/Testcases/SuperAdmin/test_8_Remove_Exclusion_and_Validate.py
  displayName: 'Validate Removed Exclusion'
  continueOnError: true
  condition: always()

- script: |
    pytest Auto/Testcases/SuperAdmin/test_9_Upload_Csv_and_Validate.py
  displayName: 'Validate CSV Translation'
  continueOnError: true
  condition: always()
  
- script: |
    pytest Auto/Testcases/SuperAdmin/test__10_Add_Customfontsize_and_Validate.py
  displayName: 'Validate added Fontsize'
  continueOnError: true
  condition: always()
  
- script: |
    pytest Auto/Testcases/SuperAdmin/test__11_Remove_Customfontsize_and_validate.py
  displayName: 'Validate Removed Fontsize'
  continueOnError: true
  condition: always()

- script: |
    pytest Auto/Testcases/SuperAdmin/test__12_Add_New_URL_validate_Preview.py
  displayName: 'Add New URL and validate Preview'
  continueOnError: true
  condition: always()

- script: |
    pytest Auto/Testcases/SuperAdmin/test__13_Delete_Project.py
  displayName: 'Delete Project'
  continueOnError: true
  condition: always()