# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

schedules:
- cron: "0 18 * * Mon"
  displayName: Daily midnight build
  branches:
    include:
    - master
    
trigger:
- master

pool:
  vmImage: 'vs2017-win2016'
strategy:
  matrix:
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install selenium
    pip install pytest
    pip install pytest_check
  displayName: 'Install dependencies'


- script: |
    pytest Testcases/SuperAdmin/test_1_login.py
  displayName: 'Login'
  continueOnError: true
  condition: always()

- script: |
    pytest Testcases/SuperAdmin/test_2_Create_Organization.py
  displayName: 'Create Organization'
  continueOnError: true
  condition: always()

- script: |
    pytest Testcases/SuperAdmin/test_3_Create_Users.py
  displayName: 'Create Users'
  continueOnError: true
  condition: always()

- script: |
    pytest Testcases/SuperAdmin/test_4_Edit_User.py
  displayName: 'Edit Users'
  continueOnError: true
  condition: always()

- script: |
    pytest Testcases/SuperAdmin/test_5_Edit_Organization.py
  displayName: 'Edit Organiztion'
  continueOnError: true
  condition: always()
  

- script: |
    pytest Testcases/SuperAdmin/test_6_Delete_Users.py
  displayName: 'Delete Users'
  continueOnError: true
  condition: always()

- script: |
    pytest Testcases/SuperAdmin/test_7_Delete_Organization.py
  displayName: 'Delete Organiztion'
  continueOnError: true
  condition: always()

- script: |
    pytest Testcases/SuperAdmin/test_8_Create_Project.py
  displayName: 'Create Project'
  continueOnError: true
  condition: always()
  
- script: |
    pytest Testcases/SuperAdmin/test_9_Preview_Localization.py
  displayName: 'Preview Localiztion Page'
  continueOnError: true
  condition: always()
  
- script: |
    pytest Testcases/SuperAdmin/test__10_Add_Exclusion_and_Validate.py
  displayName: 'Add Exclusion and Validate'
  continueOnError: true
  condition: always()

- script: |
    pytest Testcases/SuperAdmin/test__11_Remove_Exclusion_and_Validate.py
  displayName: 'Remove Exclusion and Validate'
  continueOnError: true
  condition: always()

- script: |
    pytest Testcases/SuperAdmin/test__12_Upload_Csv_and_Validate.py
  displayName: 'Upload Translations and Validate'
  continueOnError: true
  condition: always()

- script: |
    pytest Testcases/SuperAdmin/test__13_Add_Customfontsize_and_Validate.py
  displayName: 'Add Font and Validate'
  continueOnError: true
  condition: always()

- script: |
    pytest Testcases/SuperAdmin/test__14_Remove_Customfontsize_and_validate.py
  displayName: 'Remove Font and Validate'
  continueOnError: true
  condition: always()

- script: |
    pytest Testcases/SuperAdmin/test__15_Add_New_URL_validate_Preview.py
  displayName: 'Add New URL and validate Preview'
  continueOnError: true
  condition: always()

- script: |
    pytest Testcases/SuperAdmin/test__16_Delete_Project.py
  displayName: 'Delete Project'
  continueOnError: true
  condition: always()