from selenium import webdriver
import unittest
import random
import string
import time
from selenium.common.exceptions import NoSuchElementException, ElementClickInterceptedException
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.options import Options 
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException

class Createpbktpeprojectmixin:

    def __init__(self):
        print("Create Project")

    def Login_To_Anuvadak(self):
        
        self.driver.implicitly_wait(10)
        self.driver.find_element_by_id("normal_login_email").send_keys(self.qa_username)
        self.driver.find_element_by_id("normal_login_password").send_keys(self.qa_password)
        self.driver.find_element_by_xpath("//text()[.='Log in']/ancestor::button[1]").click()
        print("Logged in to Anuvadhak as Super Admin")
    
    def Create_Prabandhak_Project_Translation(self):

        self.driver.implicitly_wait(10)
        self.driver.find_element_by_xpath("//span[@title='Filter menu']").click()
        self.driver.find_element_by_xpath("//input[@class='ant-input']").send_keys("QA Test",Keys.ENTER)
        self.driver.find_element_by_xpath("//td[@class='ant-table-selection-column']//label[1]").click()
        self.driver.find_element_by_css_selector("button[id='create-user']").click()
        self.driver.find_element_by_id("AddPrject_name").send_keys("Projectx1")
        self.driver.find_element_by_name("baseUrl").send_keys("https://anuvadhaqa.wordpress.com/")
        self.driver.find_element_by_id("AddPrject_language").click()
        self.driver.find_element_by_xpath("//*[text()='hindi']").click()
        self.driver.find_element_by_xpath("//*[text()='Choose All']").click()
        self.driver.find_element_by_xpath("//span[text()='Manual']").click()
        time.sleep(1)
        self.driver.find_element_by_xpath("//button[contains(@class,'ant-btn ant-dropdown-trigger')]").click()
        time.sleep(1)
        self.driver.find_element_by_xpath("//li[text()='Translation -> Proofreading -> Editing']").click()
        self.driver.find_element_by_xpath("(//input[@class='ant-select-search__field'])[2]").send_keys("https://anuvadhaqa.wordpress.com/blog/", Keys.ENTER)
        #self.driver.find_element_by_xpath("(//input[@class='ant-select-search__field'])[2]").send_keys("https://anuvadhaqa.wordpress.com/about/",Keys.ENTER)
        time.sleep(2)
        self.driver.find_element_by_xpath("(//input[@class='c-pointer'])[2]").click()
        time.sleep(30)
        self.driver.refresh()
        print("Prabandhak Project Created Successfully")
        self.driver.close()

    def Login_To_Anuvadak_Lsp_Account(self):
        

        self.driver.find_element_by_name("email").send_keys(self.lsp_username)
        self.driver.find_element_by_name("password").send_keys(self.lsp_password)
        self.driver.find_element_by_class_name("jss156").click()
        print("Logged into Prabandhak as Anuvadhak_Lsp")
        time.sleep(5)
        self.driver.refresh()
        self.driver.find_element_by_xpath("//span[text()='My Projects']").click()
        self.driver.find_element_by_xpath("//span[text()='In-House Project']").click()
        time.sleep(2)
        self.driver.find_element_by_xpath("//input[@placeholder='Search Project']").send_keys("Anuv",Keys.ENTER)
        #time.sleep(1)
        self.driver.find_element_by_xpath("//span[text()='Files processed']").click()
        self.driver.find_element_by_xpath("//*[text()='Project Overview']").click()
        #time.sleep(5)
        self.driver.find_element_by_xpath("//*[text()='Publish']").click()
        self.driver.find_element_by_xpath("//*[text()='Yes']").click()
        time.sleep(2)
        print("Project Published Successfully")
        self.driver.find_element_by_xpath("//*[text()='Add Team members']").click()
        time.sleep(2)
        self.driver.find_element_by_id("select-targetLanguage").click()
        self.driver.find_element_by_id("select-targetLanguage").click()
        self.driver.find_element_by_css_selector("li[data-value='hindi']").click()
        self.driver.find_element_by_id("select-service").click()
        self.driver.find_element_by_css_selector("li[data-value='translation']").click()
        time.sleep(2)
        self.driver.find_element_by_xpath("//input[@placeholder='Search User']").send_keys("qatran",Keys.ENTER)
        self.driver.find_element_by_id("754a2819-c3f8-4a74-8669-d6e07b896cc2").click()
        self.driver.find_element_by_id("wordCount").send_keys("999")
        time.sleep(2)
        self.driver.find_element_by_xpath("//*[text()='Allocate']").click() 
        time.sleep(2)
        print("Project Assigned to Translator Successfully")
        self.driver.find_element_by_id("select-targetLanguage").click()
        self.driver.find_element_by_id("select-targetLanguage").click()
        self.driver.find_element_by_css_selector("li[data-value='hindi']").click()
        self.driver.find_element_by_id("select-service").click()
        self.driver.find_element_by_css_selector("li[data-value='proofreading']").click()
        time.sleep(2)
        self.driver.find_element_by_xpath("//input[@placeholder='Search User']").send_keys("qaproo",Keys.ENTER)
        self.driver.find_element_by_id("6ff11ae5-627e-4803-a763-9a1e9b59f360").click()
        self.driver.find_element_by_id("wordCount").send_keys("999")
        time.sleep(2)
        self.driver.find_element_by_xpath("//*[text()='Allocate']").click()
        print("Project Assigned to Proofreader successfully") 
        time.sleep(2)
        self.driver.find_element_by_id("select-targetLanguage").click()
        self.driver.find_element_by_id("select-targetLanguage").click()
        self.driver.find_element_by_css_selector("li[data-value='hindi']").click()
        self.driver.find_element_by_id("select-service").click()
        self.driver.find_element_by_css_selector("li[data-value='editing']").click()
        time.sleep(2)
        self.driver.find_element_by_xpath("//input[@placeholder='Search User']").send_keys("qaedit",Keys.ENTER)
        self.driver.find_element_by_id("3dbb682f-44df-4ff3-b26d-fad93a580970").click()
        self.driver.find_element_by_id("wordCount").send_keys("999")
        time.sleep(2)
        self.driver.find_element_by_xpath("//*[text()='Allocate']").click() 
        time.sleep(2)
        print("Project assigned to Editor Successfully")
        self.driver.close()
    
    def Login_To_Associate_perform_Translations(self):
        
        self.driver.implicitly_wait(10)
        self.driver.find_element_by_name("email").send_keys(self.translator_username)
        self.driver.find_element_by_name("password").send_keys(self.translator_password)
        self.driver.find_element_by_class_name("jss156").click()
        print("Logged into Prabandhak as a Translator")
        time.sleep(5)
        self.driver.refresh()
        self.driver.find_element_by_xpath("//span[text()='My Projects']").click()
        self.driver.find_element_by_xpath("//span[text()='In-House Project']").click()
        time.sleep(2)
        self.driver.find_element_by_xpath("//input[@placeholder='Search Project']").send_keys("Anuv",Keys.ENTER)
        self.driver.find_element_by_xpath("(//span[text()='Published'])[1]").click()
        self.driver.find_element_by_xpath("//span[text()='View']").click()
        time.sleep(2)
        self.driver.find_element_by_xpath("//span[text()='Start Work']").click()
        time.sleep(1)
        self.driver.find_element_by_xpath("//span[text()='Agree']").click()
        time.sleep(2)
        self.driver.find_element_by_xpath("//input[@placeholder='Search Segment By Source']").send_keys("blog",Keys.ENTER)
        time.sleep(2)
        self.driver.find_element_by_xpath("(//div[@class='target-textarea'])[2]").click()
        self.driver.find_element_by_xpath("(//div[@class='target-textarea'])[2]").send_keys("ब्लॉग",Keys.CONTROL,Keys.ENTER)
        time.sleep(2)
        print("Translations Completed Successfully")
        self.driver.close()

    def Login_To_Associate_perform_Proofreading(self):
        
        self.driver.implicitly_wait(10)
        self.driver.find_element_by_name("email").send_keys(self.proofreader_username)
        self.driver.find_element_by_name("password").send_keys(self.proofreader_password)
        self.driver.find_element_by_class_name("jss156").click()
        print("Logged into Prabandhak as a Proofreader")
        time.sleep(5)
        self.driver.refresh()
        self.driver.find_element_by_xpath("//span[text()='My Projects']").click()
        self.driver.find_element_by_xpath("//span[text()='In-House Project']").click()
        time.sleep(2)
        self.driver.find_element_by_xpath("//input[@placeholder='Search Project']").send_keys("Anuv",Keys.ENTER)
        self.driver.find_element_by_xpath("(//span[text()='Published'])[1]").click()
        self.driver.find_element_by_xpath("//span[text()='View']").click()
        time.sleep(2)
        self.driver.find_element_by_xpath("//span[text()='Start Work']").click()
        time.sleep(1)
        self.driver.find_element_by_xpath("//span[text()='Agree']").click()
        time.sleep(2)
        self.driver.find_element_by_xpath("//input[@placeholder='Search Segment By Source']").send_keys("blog",Keys.ENTER)
        time.sleep(2)
        self.driver.find_element_by_xpath("(//div[@class='target-textarea'])[1]").click()
        self.driver.find_element_by_xpath("(//div[@class='target-textarea'])[1]").send_keys(Keys.CONTROL,Keys.ENTER)
        time.sleep(2)
        print("Proofreading Completed Successfully")
        self.driver.close()
    
    def Login_To_Associate_perform_Editing(self):
        
        self.driver.implicitly_wait(10)
        self.driver.find_element_by_name("email").send_keys(self.editor_username)
        self.driver.find_element_by_name("password").send_keys(self.editor_password)
        self.driver.find_element_by_class_name("jss156").click()
        print("Logged into Prabandhak as a Editor")
        time.sleep(5)
        self.driver.refresh()
        self.driver.find_element_by_xpath("//span[text()='My Projects']").click()
        self.driver.find_element_by_xpath("//span[text()='In-House Project']").click()
        time.sleep(2)
        self.driver.find_element_by_xpath("//input[@placeholder='Search Project']").send_keys("Anuv",Keys.ENTER)
        self.driver.find_element_by_xpath("(//span[text()='Published'])[1]").click()
        self.driver.find_element_by_xpath("//span[text()='View']").click()
        time.sleep(2)
        self.driver.find_element_by_xpath("//span[text()='Start Work']").click()
        time.sleep(1)
        self.driver.find_element_by_xpath("//span[text()='Agree']").click()
        time.sleep(2)
        self.driver.find_element_by_xpath("//input[@placeholder='Search Segment By Source']").send_keys("blog",Keys.ENTER)
        time.sleep(2)
        self.driver.find_element_by_xpath("(//div[@class='target-textarea'])[1]").click()
        self.driver.find_element_by_xpath("(//div[@class='target-textarea'])[1]").send_keys(Keys.CONTROL,Keys.ENTER)
        time.sleep(2)
        print("Editing Completed Successfully")
        self.driver.close()

    def Call_Webhook(self):
        
        self.driver.implicitly_wait(10)
        self.driver.find_element_by_name("email").send_keys(self.lsp_username)
        self.driver.find_element_by_name("password").send_keys(self.lsp_password)
        self.driver.find_element_by_class_name("jss156").click()
        print("Logged in as Anuvadhak_Lsp")
        time.sleep(5)
        self.driver.refresh()
        self.driver.find_element_by_xpath("//span[text()='My Projects']").click()
        self.driver.find_element_by_xpath("//span[text()='In-House Project']").click()
        time.sleep(2)
        self.driver.find_element_by_xpath("//input[@placeholder='Search Project']").send_keys("Anuv",Keys.ENTER)
        time.sleep(1)
        self.driver.find_element_by_xpath("(//span[text()='Published'])[1]").click()
        self.driver.find_element_by_xpath("//*[text()='Project Overview']").click()
        time.sleep(2)
        self.driver.find_element_by_xpath("//span[text()='Webhook']").click()
        time.sleep(2)
        print("Webhook Triggered Successfully")
        self.driver.close()
    
    def Preview_Loclization_via_Anuvadak(self):

        self.driver.implicitly_wait(10)
        self.driver.find_element_by_id("normal_login_email").send_keys(self.qa_username)
        self.driver.find_element_by_id("normal_login_password").send_keys(self.qa_password)
        self.driver.find_element_by_xpath("//text()[.='Log in']/ancestor::button[1]").click()
        print("Logged in to Anuvadhak")
        self.driver.find_element_by_xpath("//span[@title='Filter menu']").click()
        self.driver.find_element_by_xpath("//input[@class='ant-input']").send_keys("QA Test",Keys.ENTER)
        self.driver.find_element_by_xpath("//i[@class='fas fa-external-link-alt']").click()
        time.sleep(2)
        self.driver.find_element_by_xpath("(//tbody/tr[1]/td[6]/span[1]//*[local-name()='svg'])[1]").click()
        self.driver.find_element_by_xpath("//input[@id='ImmediateCacheFlush_allow_urls']").send_keys("https://anuvadhaqa.wordpress.com/blog",Keys.ENTER)
        self.driver.find_element_by_name("isForWebsite").click()
        self.driver.find_element_by_xpath("//input[@value='Flush']").click()
        print("Flushed cace successfully")
        time.sleep(10)
        self.driver.find_element_by_xpath("(//div[@role='button'])[1]").click()
        self.driver.find_element_by_xpath("//button[@class='c-pointer loc-preview-btn']").click()
        time.sleep(1)
        self.driver.find_element_by_xpath("//button[contains(@class,'ant-btn ant-dropdown-trigger')]").click()
        time.sleep(1)
        self.driver.find_element_by_xpath("//*[text()='hindi']").click()
        self.driver.find_element_by_link_text("https://anuvadhaqa.wordpress.com/blog").click()
        self.driver.switch_to.window(self.driver.window_handles[1])
        self.driver.find_element_by_xpath("//h1[text()='ब्लॉग']").click()
        print("Previewed Section successfully")
        self.driver.close()
        self.driver.switch_to.window(self.driver.window_handles[0])
        self.driver.close()
    
    def Deleteproject_with_TM(self): 
        
        self.driver.implicitly_wait(10)
        self.driver.find_element_by_id("normal_login_email").send_keys(self.qa_username)
        self.driver.find_element_by_id("normal_login_password").send_keys(self.qa_password)
        self.driver.find_element_by_xpath("//text()[.='Log in']/ancestor::button[1]").click()
        print("Logged in to Anuvadhak")
        self.driver.find_element_by_xpath("//span[@title='Filter menu']").click()
        self.driver.find_element_by_xpath("//input[@class='ant-input']").send_keys("QA Test",Keys.ENTER)
        self.driver.find_element_by_xpath("//i[@class='fas fa-external-link-alt']").click()
        self.driver.find_element_by_xpath("(//tbody/tr[1]/td[6]/span[1]//*[local-name()='svg'])[4]").click()
        self.driver.find_element_by_xpath("(//li[@role='menuitem'])[3]").click()
        time.sleep(2)
        self.driver.find_element_by_xpath("(//button[@type='button'])[3]").click()
        time.sleep(2)
        self.driver.find_element_by_id("projectName").send_keys("Projectx1")
        time.sleep(2)
        self.driver.find_element_by_xpath("//input[@value='Delete TM']").click()
        time.sleep(10)
        print("Deleted Project Successfully")
        self.driver.close()
